-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: Create activity_signals table — LPI Platform Phase 3
-- Owner  : Adil Islam
-- Date   : 2026-06-11
-- ─────────────────────────────────────────────────────────────────────────────
--
-- WHY THIS TABLE EXISTS
-- ─────────────────────
-- Activity signals are the raw evidence of what a user actually DID.
-- A goal says "I want to build a startup". A signal says "Alice merged a PR".
-- The recommendation engine (Phase 4, Jaivardhan) reads goals + signals
-- together to output concrete next-action instructions. Without this table,
-- Phase 4 has nothing to read from.
--
-- FIELD DESIGN
-- ─────────────
-- stream      : WHICH business domain the signal belongs to.
--               Examples: 'lpi', 'boardy', 'datapro', 'vsab'
--               NOT the ingestion mechanism — that is `source`.
--
-- event_type  : WHAT happened within that stream.
--               Examples: 'pr_merged', 'commit_pushed', 'match_created'
--
-- payload     : Raw event data as JSON. Flexible — every source has
--               different fields. The recommendation engine parses this.
--               Examples:
--                 {"repo": "lpi-platform", "pr_number": 18}   (GitHub)
--                 {"person_a": "Alice", "score": 0.85}        (Boardy)
--
-- source      : HOW the signal was ingested. Not the stream topic.
--               Values:
--                 'github_api'  — pulled from GitHub Events API (verified real)
--                 'manual'      — entered by a human via the API directly
--                 'simulated'   — generated by a test/seed script (not real)
--                 'api'         — sent via REST API with no specific source tag
--
--               WHY source EXISTS NOW (Phase 3, not Phase 4):
--               The recommendation engine needs to WEIGHT signals differently.
--               A real GitHub commit is stronger evidence than a simulated one.
--               Adding `source` now means Phase 4 never needs a breaking
--               schema migration — the column is already there.
--               It defaults to 'api' so existing API callers need no changes.
--
-- INDEXES
-- ────────
-- Each CREATE INDEX below tells Postgres: "build a fast lookup structure
-- for this column." Without indexes, every filter (?stream=boardy) would
-- scan every single row — O(n). With indexes, Postgres jumps directly to
-- matching rows — O(log n). At 10,000 signals, that's the difference
-- between 10ms and 10,000ms.
--
-- HOW TO APPLY THIS MIGRATION
-- ─────────────────────────────
-- Local dev:   supabase db push     (applies all unapplied migrations)
-- Verify:      supabase status      (check migration is listed)
-- Studio:      http://127.0.0.1:54323 → Table Editor → activity_signals
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS activity_signals (
    -- id: generated by Python (uuid.uuid4()), not by Postgres.
    -- TEXT type matches the goals table convention in this project.
    id          TEXT        PRIMARY KEY,

    -- user_id: whose signal this is. Phase 3 = 'default_user' stub.
    -- Phase 4: real JWT subject from get_current_user().
    user_id     TEXT        NOT NULL DEFAULT 'default_user',

    -- stream: which business domain (lpi, boardy, datapro, vsab, altiostar).
    -- No CHECK constraint intentionally — new streams can be added without
    -- a schema migration. The application layer validates if needed.
    stream      TEXT        NOT NULL,

    -- event_type: what happened (pr_merged, match_created, commit_pushed).
    -- No CHECK constraint — event types grow as real streams integrate.
    event_type  TEXT        NOT NULL,

    -- payload: flexible JSON blob. Every event source has different fields.
    -- JSONB (binary JSON) is faster to query than plain JSON in Postgres.
    -- Defaults to empty object so callers don't need to send it explicitly.
    payload     JSONB       NOT NULL DEFAULT '{}',

    -- source: how was this signal ingested?
    -- See field design comment above for full explanation.
    -- DEFAULT 'api' means existing test payloads need no changes.
    source      TEXT        NOT NULL DEFAULT 'api',

    -- timestamp: when the event happened (or when it was ingested).
    -- Set by Python (datetime.now(UTC)) so it's consistent across all inserts.
    -- TIMESTAMPTZ stores timezone — always UTC here.
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
-- These make the server-side filter queries fast.
-- Pattern: one index per column you expect to filter or sort by.

-- Filter by user: GET /signals/?user_id=alice (Phase 4 will use this heavily)
CREATE INDEX IF NOT EXISTS idx_as_user_id
    ON activity_signals (user_id);

-- Filter by stream: GET /signals/?stream=boardy
CREATE INDEX IF NOT EXISTS idx_as_stream
    ON activity_signals (stream);

-- Filter by event type: GET /signals/?event_type=pr_merged
CREATE INDEX IF NOT EXISTS idx_as_event_type
    ON activity_signals (event_type);

-- Filter by source: GET /signals/?source=github_api
-- Phase 4 recommendation engine uses this to exclude simulated signals.
CREATE INDEX IF NOT EXISTS idx_as_source
    ON activity_signals (source);

-- Sort by timestamp: default ordering is newest-first.
-- DESC index means Postgres doesn't need to reverse-sort after fetching.
CREATE INDEX IF NOT EXISTS idx_as_timestamp
    ON activity_signals (timestamp DESC);
